title: Mozilla Releases
description: "A blog of automated and manual posts regarding Mozilla releases"
email: release-mgmt@mozilla.com
baseurl: ""
github: "http://github.com/mozilla/release-blog"
markdown: redcarpet
pygments: true

# Navigation
navigation:
- title: Team Wiki
  url: http://wiki.mozilla.org/Release_Management
- title: Blog
  url: /index.html
